Update docker-image.yml
still testing

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,20 +1,52 @@
-name: Docker Image CI
+name: Build and Push
 
 on:
   push:
-    branches: [ "master" ]
-  pull_request:
-    branches: [ "master" ]
+    branches:
+      - main
+
+permissions:
+  contents: read
+  packages: write
 
 jobs:
-
-  build:
-
+  docker:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v6
-    - name: Build the App
-      run: docker build . --file DockerfileBuild
-    - name: Build the Docker image
-      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
+      - name: Checkout
+        uses: actions/checkout@v5
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build application
+        run: |
+          rm -rf build
+
+          docker build \
+            -t docker-build \
+            -f DockerfileBuild \
+            .
+
+          docker run --rm \
+            -v "${{ github.workspace }}/build:/build" \
+            docker-build
+
+          if [ ! -d build ] || [ -z "$(ls -A build)" ]; then
+            echo "Build failed"
+            exit 1
+          fi
+
+          rm -rf build/runtimes/win*
+          rm -rf build/runtimes/osx*
+          rm -rf build/ru-*
+
+      - name: Build and Push Docker image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: Dockerfile
+          platforms: linux/amd64
+          push: true
+          tags: ghcr.io/${{ github.repository_owner }}/fenrus:latest
